// Nynorsk + English strings + theme directions

const I18N = {
  nn: {
    appName: "Crate",
    tagline: "Plata di. Hånda di.",
    search: "Søk i samlinga",
    sort_artist: "Artist",
    sort_title: "Tittel",
    sort_year: "År",
    sort_added: "Lagt til",
    view_flip: "Bla",
    view_grid: "Rutenett",
    in_collection: "i samlinga",
    sync: "Synkroniserer med Discogs",
    sync_done: "Synk fullført",
    of: "av",
    records: "plater",
    play_side: "Skrobble side",
    play_album: "Skrobble heile albumet",
    play_track: "Skrobble dette sporet",
    update_release: "Oppdater platedata",
    side: "Side",
    track: "Spor",
    duration: "Lengd",
    label: "Etikett",
    format: "Format",
    country: "Land",
    year: "År",
    genres: "Sjangrar",
    styles: "Stilar",
    rating: "Vurdering",
    notes: "Notar",
    videos: "Videoar",
    close: "Lukk",
    now_playing: "No spelar",
    next_track: "Neste",
    prev_track: "Førre",
    pause: "Pause",
    resume: "Spel",
    stop: "Stopp",
    elapsed: "Spelt",
    remaining: "Att",
    open_full: "Opne fullskjerm",
    side_a: "SIDE A",

    // Auth
    welcome: "Velkomen til Crate",
    welcome_sub: "Logg inn for å sjå platesamlinga di",
    username: "Brukarnamn",
    password: "Passord",
    confirm_password: "Stadfest passord",
    log_in: "Logg inn",
    sign_up: "Registrer",
    new_user: "Ny brukar?",
    have_account: "Har konto?",
    create_account: "Lag ny konto",
    back_to_login: "Tilbake til innlogging",
    err_invalid_login: "Feil brukarnamn eller passord",
    err_passwords_match: "Passorda er ikkje like",
    err_too_short: "Passordet må vere minst 8 teikn",
    err_username_taken: "Brukarnamnet finst allereie",
    show_password: "Vis passord",
    hide_password: "Gøym passord",

    // Onboarding
    onboard_title: "Kople til kontoane dine",
    onboard_sub: "Crate les samlinga di frå Discogs og skrobblar til Last.fm",
    step: "Steg",
    step_discogs: "Kople Discogs",
    step_lastfm: "Kople Last.fm",
    step_done: "Klar",
    discogs_desc: "Crate brukar Discogs til å hente plateinformasjon, omslagsbilete og sporsettlister.",
    lastfm_desc: "Crate skrobblar musikken du spelar til Last.fm-kontoen din. Lyttehistorikken di blir bevart.",
    connect: "Kople til",
    connected: "Kopla",
    skip_for_now: "Hopp over for no",
    finish_setup: "Ferdigstill oppsett",
    open_app: "Opne Crate",
    waiting_authorize: "Ventar på autorisasjon …",

    // Settings
    settings: "Innstillingar",
    theme_label: "Tema",
    appearance: "Utsjånad",
    light_mode: "Lyst",
    dark_mode: "Mørkt",
    pairing: "Typografi",
    density_label: "Tettleik",
    density_tight: "Tett",
    density_comfortable: "Komf.",
    density_spacious: "Luftig",
    now_playing_label: "No-spelar",
    np_bar: "Botn-bar",
    np_expanded: "Spinnande plate",
    np_side: "Sidepanel",
    reflection_label: "Spegelrefleks",
    language_label: "Språk",
    accounts: "Kontoar",
    log_out: "Logg ut",
    discogs: "Discogs",
    lastfm: "Last.fm",

    // Empty / error states
    empty_collection_title: "Samlinga er tom",
    empty_collection_sub: "Crate les samlinga di frå Discogs. Ho dukkar opp her når synkronisering er ferdig.",
    no_results_title: "Ingen treff",
    no_results_sub: "Prøv eit anna søkeord, eller fjern filteret.",
    offline_title: "Ikkje på nett",
    offline_sub: "Kunne ikkje nå Discogs. Sjekk nettsambandet og prøv på nytt.",
    retry: "Prøv på nytt",
    syncing_records: "synkroniserer",
  },
  en: {
    appName: "Crate",
    tagline: "Your record. Your hand.",
    search: "Search collection",
    sort_artist: "Artist",
    sort_title: "Title",
    sort_year: "Year",
    sort_added: "Added",
    view_flip: "Flip",
    view_grid: "Grid",
    in_collection: "in collection",
    sync: "Syncing with Discogs",
    sync_done: "Sync complete",
    of: "of",
    records: "records",
    play_side: "Scrobble side",
    play_album: "Scrobble whole album",
    play_track: "Scrobble this track",
    update_release: "Refresh release data",
    side: "Side",
    track: "Track",
    duration: "Length",
    label: "Label",
    format: "Format",
    country: "Country",
    year: "Year",
    genres: "Genres",
    styles: "Styles",
    rating: "Rating",
    notes: "Notes",
    videos: "Videos",
    close: "Close",
    now_playing: "Now playing",
    next_track: "Next",
    prev_track: "Prev",
    pause: "Pause",
    resume: "Play",
    stop: "Stop",
    elapsed: "Elapsed",
    remaining: "Left",
    open_full: "Open full",
    side_a: "SIDE A",

    // Auth
    welcome: "Welcome to Crate",
    welcome_sub: "Sign in to see your record collection",
    username: "Username",
    password: "Password",
    confirm_password: "Confirm password",
    log_in: "Sign in",
    sign_up: "Sign up",
    new_user: "New user?",
    have_account: "Have an account?",
    create_account: "Create account",
    back_to_login: "Back to sign in",
    err_invalid_login: "Wrong username or password",
    err_passwords_match: "Passwords don't match",
    err_too_short: "Password must be at least 8 characters",
    err_username_taken: "Username already taken",
    show_password: "Show password",
    hide_password: "Hide password",

    // Onboarding
    onboard_title: "Connect your accounts",
    onboard_sub: "Crate reads your collection from Discogs and scrobbles to Last.fm",
    step: "Step",
    step_discogs: "Connect Discogs",
    step_lastfm: "Connect Last.fm",
    step_done: "Ready",
    discogs_desc: "Crate uses Discogs to fetch record metadata, cover art and tracklists.",
    lastfm_desc: "Crate scrobbles the music you play to your Last.fm account. Your listening history is preserved.",
    connect: "Connect",
    connected: "Connected",
    skip_for_now: "Skip for now",
    finish_setup: "Finish setup",
    open_app: "Open Crate",
    waiting_authorize: "Waiting for authorization …",

    // Settings
    settings: "Settings",
    theme_label: "Theme",
    appearance: "Appearance",
    light_mode: "Light",
    dark_mode: "Dark",
    pairing: "Typography",
    density_label: "Density",
    density_tight: "Tight",
    density_comfortable: "Comf.",
    density_spacious: "Spacious",
    now_playing_label: "Now playing",
    np_bar: "Bottom bar",
    np_expanded: "Spinning record",
    np_side: "Side panel",
    reflection_label: "Sleeve reflection",
    language_label: "Language",
    accounts: "Accounts",
    log_out: "Sign out",
    discogs: "Discogs",
    lastfm: "Last.fm",

    // Empty / error states
    empty_collection_title: "Collection is empty",
    empty_collection_sub: "Crate reads your collection from Discogs. It'll appear here when sync completes.",
    no_results_title: "No results",
    no_results_sub: "Try a different search term, or clear the filter.",
    offline_title: "Offline",
    offline_sub: "Couldn't reach Discogs. Check your network and try again.",
    retry: "Retry",
    syncing_records: "syncing",
  },
};

// Three audiophile directions. Each carries its own accent + texture vocabulary.
const DIRECTIONS = {
  studio: {
    name: "Studio",
    tag: "Brushed chrome · electric cyan",
    // Dark
    dark: {
      bg: "#0a0b0d",
      surface: "#111316",
      surface2: "#181a1e",
      ink: "#e8eaee",
      inkMuted: "#8a8f96",
      inkDim: "#4e525a",
      hairline: "rgba(255,255,255,0.08)",
      hairlineStrong: "rgba(255,255,255,0.16)",
      accent: "#19D1F8",
      accentInk: "#001016",
      grain: 0.04,
    },
    light: {
      bg: "#f3f4f6",
      surface: "#ffffff",
      surface2: "#eaecef",
      ink: "#0c0d0f",
      inkMuted: "#5a5f66",
      inkDim: "#9aa0a8",
      hairline: "rgba(0,0,0,0.10)",
      hairlineStrong: "rgba(0,0,0,0.20)",
      accent: "#0288A6",
      accentInk: "#ffffff",
      grain: 0,
    },
    feel: { uppercase: true, letterSpacing: "0.08em", titleSerif: false },
  },
  vinyl: {
    name: "Vinyl",
    tag: "Cream paper · oxblood",
    dark: {
      bg: "#100d0c",
      surface: "#1a1614",
      surface2: "#221d1a",
      ink: "#ece3d4",
      inkMuted: "#9c8f7d",
      inkDim: "#5a4f44",
      hairline: "rgba(236,227,212,0.10)",
      hairlineStrong: "rgba(236,227,212,0.22)",
      accent: "#C73E3A",
      accentInk: "#fff5ec",
      grain: 0.08,
    },
    light: {
      bg: "#f4ede1",
      surface: "#ffffff",
      surface2: "#ece5d6",
      ink: "#1a1310",
      inkMuted: "#6b5d50",
      inkDim: "#a89c8a",
      hairline: "rgba(26,19,16,0.10)",
      hairlineStrong: "rgba(26,19,16,0.25)",
      accent: "#A8302C",
      accentInk: "#fff5ec",
      grain: 0.03,
    },
    feel: { uppercase: false, letterSpacing: "0.02em", titleSerif: true },
  },
  vu: {
    name: "VU",
    tag: "Phosphor green · matte black",
    dark: {
      bg: "#070808",
      surface: "#0e1010",
      surface2: "#141716",
      ink: "#dde7da",
      inkMuted: "#7a857a",
      inkDim: "#454c46",
      hairline: "rgba(127,227,137,0.10)",
      hairlineStrong: "rgba(127,227,137,0.24)",
      accent: "#7FE389",
      accentInk: "#031006",
      grain: 0.06,
    },
    light: {
      bg: "#e8ece8",
      surface: "#ffffff",
      surface2: "#dde3dc",
      ink: "#091210",
      inkMuted: "#4f5a52",
      inkDim: "#8a948c",
      hairline: "rgba(9,18,16,0.12)",
      hairlineStrong: "rgba(9,18,16,0.24)",
      accent: "#1F8A4B",
      accentInk: "#f0fff2",
      grain: 0,
    },
    feel: { uppercase: true, letterSpacing: "0.10em", titleSerif: false },
  },
  paper: {
    name: "Paper",
    tag: "Liner notes · daylight editorial",
    dark: {
      bg: "#1c1a16",
      surface: "#26231e",
      surface2: "#2d2922",
      ink: "#f5ecd9",
      inkMuted: "#a89878",
      inkDim: "#5a5240",
      hairline: "rgba(245,236,217,0.10)",
      hairlineStrong: "rgba(245,236,217,0.22)",
      accent: "#D4A24A",
      accentInk: "#1a1410",
      grain: 0.06,
    },
    light: {
      bg: "#f5efe0",
      surface: "#fffaeb",
      surface2: "#ece4d0",
      ink: "#1a1612",
      inkMuted: "#6a5d48",
      inkDim: "#a89880",
      hairline: "rgba(26,22,18,0.10)",
      hairlineStrong: "rgba(26,22,18,0.25)",
      accent: "#A8782A",
      accentInk: "#fffaeb",
      grain: 0.02,
    },
    feel: { uppercase: false, letterSpacing: "0.015em", titleSerif: true },
  },
  sodium: {
    name: "Sodium",
    tag: "Tungsten lamp · deep amber",
    dark: {
      bg: "#0c0908",
      surface: "#15110e",
      surface2: "#1c1812",
      ink: "#ffd9a3",
      inkMuted: "#8a7558",
      inkDim: "#4a4032",
      hairline: "rgba(255,217,163,0.10)",
      hairlineStrong: "rgba(255,217,163,0.26)",
      accent: "#F5A623",
      accentInk: "#1c0f00",
      grain: 0.05,
    },
    light: {
      bg: "#fbf3e3",
      surface: "#ffffff",
      surface2: "#f0e6cf",
      ink: "#1c130a",
      inkMuted: "#6c5a40",
      inkDim: "#a89478",
      hairline: "rgba(28,19,10,0.10)",
      hairlineStrong: "rgba(28,19,10,0.24)",
      accent: "#B8762A",
      accentInk: "#fbf3e3",
      grain: 0,
    },
    feel: { uppercase: true, letterSpacing: "0.08em", titleSerif: false },
  },
};

// Typography pairings
const TYPE_PAIRINGS = {
  classic: {
    name: "Klassisk",
    display: "'Cormorant Garamond', 'Times New Roman', serif",
    ui: "'Inter Tight', 'Helvetica Neue', Helvetica, Arial, sans-serif",
    mono: "'JetBrains Mono', 'Courier New', monospace",
  },
  modernist: {
    name: "Modernistisk",
    display: "'Inter Tight', 'Helvetica Neue', sans-serif",
    ui: "'Inter Tight', 'Helvetica Neue', sans-serif",
    mono: "'JetBrains Mono', 'Courier New', monospace",
  },
  hifi: {
    name: "Hi-Fi",
    display: "'Fraunces', 'Times New Roman', serif",
    ui: "'IBM Plex Sans', 'Inter Tight', sans-serif",
    mono: "'IBM Plex Mono', 'JetBrains Mono', monospace",
  },
};

window.I18N = I18N;
window.DIRECTIONS = DIRECTIONS;
window.TYPE_PAIRINGS = TYPE_PAIRINGS;
